[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
crux_core.workspace = true
serde = { workspace = true, features = ["derive"] }
lazy_static = "1.4.0"
uniffi = "0.26.1"
wasm-bindgen = "0.2.92"
futures = "0.3.30"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.26.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
